### ISSUE TITLE
CHD5.10.2's sqoop component when use --incremental throw exception

### ISSUE THREAD

**Issue by liuwei0376** [cloudera/cdh-package#3]
My current sqoop version is: Sqoop 1.4.6-cdh5.10.2

when execute command as below:

sqoop import \
--connect jdbc:oracle:thin:@//IP:PORT/XXXX \
--username ${USER} \
--password ${PASS} \
--table USERS \
--hive-import \
--hive-table USERS_TMP \
--incremental lastmodified \
--check-column UPDATE_TIME \
--last-value '2017-09-13' \
--merge-key ID --verbose \
--target-dir /user/hive/warehouse/USERS_TMP \
--hive-drop-import-delims \
--fields-terminated-by '\001' \
--m 1

It throw exception as below:

17/09/15 12:42:41 DEBUG sqoop.Sqoop: --incremental lastmodified option for hive imports is not supported. Please remove the parameter --incremental lastmodified.
--incremental lastmodified option for hive imports is not supported. Please remove the parameter --incremental lastmodified.
	at org.apache.sqoop.tool.BaseSqoopTool.validateHiveOptions(BaseSqoopTool.java:1501)
	at org.apache.sqoop.tool.ImportTool.validateOptions(ImportTool.java:1157)
	at org.apache.sqoop.Sqoop.run(Sqoop.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.sqoop.Sqoop.runSqoop(Sqoop.java:183)
	at org.apache.sqoop.Sqoop.runTool(Sqoop.java:234)
	at org.apache.sqoop.Sqoop.runTool(Sqoop.java:243)
	at org.apache.sqoop.Sqoop.main(Sqoop.java:252)
--incremental lastmodified option for hive imports is not supported. Please remove the parameter --incremental lastmodified.

I check up CDH5.10.2 release notes, it says it's a new feature that not included in the Sqoop base version 1.4.6 :
[SQOOP-2986] - Add validation check for --hive-import and --incremental lastmodified

Is the enhancement(validation check) brings this error?

By the way, when this command execute at version of Sqoop 1.4.6-cdh5.7.2, it's right, has no error.

**Comment by liuwei0376** [comment]
According to look up into the sourcecode of  CHD5.10.2 version, found that this version doesn't support --incremental --append-mode, when you use these 2 keys, it directly throw exception.
